Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NuCloudWeb.Models;

namespace NuCloudWeb.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        //View to login member
        public IActionResult LoginMember()
        {
            return View();
        }

        [HttpPost]
        //cuek
        public async Task<IActionResult> LoginMember(Member member)
        {
            long num = DB.Instance.CantMemberForCedAndPass(member.Ced, member.Password).Result;
            if (num == 1)
            {
                var miembro = DB.Instance.GetMember(member.Ced);
                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, member.Ced.ToString()));
                identity.AddClaim(new Claim(ClaimTypes.Name, miembro.Result.Name));
                identity.AddClaim(new Claim(ClaimTypes.Surname, miembro.Result.LastName));
                identity.AddClaim(new Claim(ClaimTypes.Email, miembro.Result.Email is null ? "" : miembro.Result.Email));
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal,
                    new AuthenticationProperties { ExpiresUtc = DateTime.Now.AddDays(1), IsPersistent = true });
                return RedirectToAction("Index", "Home");
            }
            else
            {
                System.Diagnostics.Debug.WriteLine("Caca fallo");
            }
            return View();
        }
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }
    }    

}

Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Neo4j.Driver;
using NuCloudWeb.Models;

namespace NuCloudWeb.Controllers {

    //[Authorize]

    public class MemberController : Controller {
        public IActionResult Index() {
            return View();
        }

        [HttpGet]
        //Instance that return view 
        [Route("Member/Member/{ced:int}")]
        public async Task<ActionResult> Member([FromRoute] int ced) {
            Member t = await DB.Instance.GetMember(ced.ToString());
            t.Leads = await DB.Instance.GetLeads(ced.ToString());
            t.Coaches = await DB.Instance.GetCoaches(ced.ToString());
            t.MemberOf = await DB.Instance.MemberOf(ced.ToString());
            return View(t);
        }

        [HttpGet]
        //View to add member
        public IActionResult AddMember() {
            return View();
        }

        [HttpPost]
        //Function that create a member
        public IActionResult AddMember(Member member) {
            long num = DB.Instance.CantMemberForCed(member.Ced).Result;
            if (num == 0)
            {
                DB.Instance.CreateMember(new Member()
                {
                    Name = member.Name,
                    LastName = member.LastName,
                    Ced = member.Ced,
                    Phone = member.Phone,
                    Password = member.Password
                });
            }            
            return View();
        }

    }
}

Views/Shared/_Layout.cshtml
@using NuCloudWeb.Helper

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NuCloudWeb</title>
    <link rel="stylesheet" href="~/css/app.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />


</head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NuCloudWeb</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="News">News</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Organization">Organization</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Organization" asp-action="Members">Members</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="AddMember">Create Members</a>
                            </li>

							@if (User.Identity.IsAuthenticated){
							    <li class="nav-item">
								    <a class="nav-link text-dark" asp-area="" asp-controller="CCG" asp-action="Inbox" asp-route-filter="all">Inbox</a>
							    </li>
							    <li class="nav-item">
								    <a class="nav-link text-dark" asp-area="" asp-controller="CCG" asp-action="Write">Write contribution</a>
							    </li>
							    <li class="nav-item">
							        <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LogOut">LogOut</a>
						        </li>
							    <br />
		                        <li style="text-align:right">
				                    Usuario Autenticado:
				                    <ul>
				                        <li> @SessionHelper.GetName(User) @SessionHelper.GetSurname(User)</li>
				                    </ul>
			                    </li>
							    
		                    }else{
		                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LoginMember">Login</a>
                                </li>
		                    }
							
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
		
		
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
			
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - NuCloudWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>